context:
  name: libmd
  version: 1.1.0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://libbsd.freedesktop.org/releases/libmd-${{ version }}.tar.xz
    sha256: 1bd6aa42275313af3141c7cf2e5b964e8b1fd488025caf2f971f43b00776b332

build:
  number: 0
  script: build-libmd.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - ${{ stdlib('c') }}
  run_exports:
    - ${{ name }}

about:
  homepage: https://www.hadrons.org/software/libmd/
  license: BSD-3-Clause AND BSD-2-Clause AND ISC AND Beerware AND LicenseRef-MD4-Public-Domain-Declaration AND LicenseRef-MD5-Public-Domain-Declaration
  license_file: 
    - COPYING
  summary: Message digest functions from BSD systems

extra:
  recipe-maintainers:
    - ethanc8
