context:
  name: gnustep-libdispatch
  version: 6.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/swiftlang/swift-corelibs-libdispatch/archive/refs/tags/swift-${{ version }}-RELEASE.tar.gz
    sha256: d4b8171d6711dabc3cb81093e954cedd521c8e4c170a688c1c369194c9eae4b3

build:
  number: 6
  script: build-libdispatch.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    - gnustep-make
    - ${{ stdlib('c') }}
  run:
    - gnustep-make
    - ${{ stdlib('c') }}
  run_exports:
    - gnustep-libdispatch

about:
  homepage: https://github.com/swiftlang/swift-corelibs-libdispatch
  license: Apache-2.0 WITH Swift-exception
  license_file: LICENSE
  summary: GNUstep Objective-C 2.0 Runtime

extra:
  recipe-maintainers:
    - ethanc8
