context:
  name: libbsd
  version: 0.12.2

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://libbsd.freedesktop.org/releases/libbsd-${{ version }}.tar.xz
    sha256: b3792acc5aa0013ef51f3d02eaaf69fcce05ca6fe9924999b3565ebeb87d9d21

build:
  number: 0
  script: build-libbsd.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
  host:
    - ${{ stdlib('c') }}
    - libmd
  run_exports:
    - ${{ name }}

about:
  homepage: https://www.hadrons.org/software/libmd/
  license: BSD-3-Clause AND BSD-2-Clause AND ISC AND Beerware AND LicenseRef-MD4-Public-Domain-Declaration AND LicenseRef-MD5-Public-Domain-Declaration
  license_file: 
    - COPYING
  summary: Message digest functions from BSD systems

extra:
  recipe-maintainers:
    - ethanc8
