context:
  name: libgnustep-gui
  # Unfortunately 0.31.1 doesn't build.
  version: 0.32.0a20241216
  # tag: gui-0_31_1
  commit: e489d43ef187b96c1e1bdd74dca6a56548791478 # 2024-12-16

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gnustep/libs-gui/archive/${{ commit }}.tar.gz
    sha256: 637bc6af3e488bd097f3f198f1df26dc861558286de5612edf4b0daa41b1f455

build:
  number: 0
  script: build-gui.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    # following https://packages.debian.org/sid/libgnustep-gui0.31 and https://github.com/gnustep/libs-gui/blob/master/INSTALL
    - ${{ stdlib('c') }}
    - gnustep-make
    - gnustep-libobjc2
    - gnustep-libdispatch
    - libgnustep-base
    - giflib
    # TODO: Make a conda package for libicns1
    - icu
    - libjpeg-turbo
    - imagemagick
    - libpng
    - libtiff
    # INSTALL recommends to have aspell, cups, audiofile, and portaudio, but Debian doesn't have those

about:
  homepage: https://github.com/gnustep/libs-gui
  license: LGPL-2.0-or-later AND GPL-2.0-or-later
  license_file: 
    - COPYING.LIB
    - COPYING
  summary: GNUstep implementation of AppKit (Cocoa-compatible GUI toolkit)

extra:
  recipe-maintainers:
    - ethanc8
