context:
  name: libgnustep-gui
  version: 0.33.0a20250512
  commit: 302d0cc90bbd418c0f52d8733eefb60d326549dd

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/gnustep/libs-gui
    rev: ${{ commit }}

build:
  number: 0
  skip: true
  script: build-gui.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    # following https://packages.debian.org/sid/libgnustep-gui0.31 and https://github.com/gnustep/libs-gui/blob/master/INSTALL
    - ${{ stdlib('c') }}
    - gnustep-make
    - gnustep-libobjc2
    - gnustep-libdispatch
    - libgnustep-base
    - giflib
    # TODO: Make a conda package for libicns1
    - icu
    - libjpeg-turbo
    - imagemagick # TODO: Make this a runtime dependency
    - libpng
    - libtiff
    # INSTALL recommends to have aspell, cups, audiofile, and portaudio, but Debian doesn't have those
  run_exports:
    - libgnustep-gui

about:
  homepage: https://github.com/gnustep/libs-gui
  license: LGPL-2.0-or-later AND GPL-2.0-or-later
  license_file: 
    - COPYING.LIB
    - COPYING
  summary: GNUstep implementation of AppKit (Cocoa-compatible GUI toolkit)

extra:
  recipe-maintainers:
    - ethanc8
