context:
  name: libgnustep-base
  version: 1.32.0a20250622
  commit: ec6299f72faa04f4bb019d4f2a0984fe832b09c0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/gnustep/libs-base
    rev: ${{ commit }}

build:
  number: 0
  skip: false
  script: build-base.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    - gnustep-make
    - gnustep-libobjc2
    - gnustep-libdispatch
    - ${{ stdlib('c') }}
    - libffi
    - icu
    - gnutls
    - libxml2
    - libxslt
    - avahi
    - zlib
    - libcurl
    - iconv
    - libiconv
  run_exports:
    - libgnustep-base


about:
  homepage: https://github.com/gnustep/libs-base
  license: LGPL-2.0-or-later AND GPL-2.0-or-later
  license_file: 
    - COPYING.LIB
    - COPYING
  summary: GNUstep implementation of Foundation Kit (Objective-C standard library)

extra:
  recipe-maintainers:
    - ethanc8
