context:
  name: libgnustep-back
  version: 0.32.0
  tag: back-0_32_0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gnustep/libs-back/archive/refs/tags/${{ tag }}.tar.gz
    sha256: e4c3a2529a6a4cfe2e2427560707059f9d7435df381bc04df95fc15e05403b3b

build:
  number: 1
  script: build-back.sh
  skip: true

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    # following https://packages.debian.org/sid/gnustep-back0.31-cairo and https://github.com/gnustep/libs-back/blob/master/INSTALL
    - ${{ stdlib('c') }}
    - gnustep-make
    - gnustep-libobjc2
    - gnustep-libdispatch
    - libgnustep-base
    - libgnustep-gui
    - cairo
    - fontconfig
    - freetype
    - libgl-devel
    - xorg-libx11
    - xorg-libxcursor
    - xorg-libxext
    - xorg-libxfixes
    - xorg-libxft
    - xorg-libxmu
    - xorg-libxrandr
    - xorg-libxrender
    - xorg-libxt
  run_exports:
    - libgnustep-back

about:
  homepage: https://github.com/gnustep/libs-back
  license: LGPL-2.0-or-later AND GPL-2.0-or-later
  license_file: 
    - COPYING.LIB
    - COPYING
  summary: Backend for libgnustep-gui

extra:
  recipe-maintainers:
    - ethanc8
