context:
  name: gnustep-make
  version: 2.9.4a${{ env.get("YYMMDD") }}

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/gnustep/tools-make

build:
  number: 0
  script: build-gsmake.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  run:
    - ${{ stdlib('c') }}
    - make

about:
  homepage: https://github.com/gnustep/tools-make
  license: GPL-3.0-only
  license_file: COPYING
  summary: GNUstep build system based on GNU Make

extra:
  recipe-maintainers:
    - ethanc8
