context:
  name: gnustep-make
  version: 2.9.3
  tag: make-2_9_3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gnustep/tools-make/archive/refs/tags/${{ tag }}.tar.gz
    sha256: aad12caecb0398b099f3b8b0282cecc3f01a9f371200641b2e1e535ae6ee2543

build:
  number: 2
  script: build-gsmake.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - lld
  run:
    - ${{ stdlib('c') }}
    - make

about:
  homepage: https://github.com/gnustep/tools-make
  license: GPL-3.0-only
  license_file: COPYING
  summary: GNUstep build system based on GNU Make

extra:
  recipe-maintainers:
    - ethanc8
