context:
  name: gnustep-libobjc2
  version: 2.3

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gnustep/libobjc2/archive/refs/tags/v${{ version }}.tar.gz
    sha256: 5ead2276b42a534ac40437ce53b2231320b985539dc325453d93874be8d92869

build:
  number: 3
  script: build-libobjc2.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    - gnustep-libdispatch
    - gnustep-make
    - ${{ stdlib('c') }}
  run:
    - gnustep-libdispatch
    - gnustep-make
    - ${{ stdlib('c') }}
  run_exports:
    - gnustep-libobjc2

about:
  homepage: https://github.com/gnustep/libobjc2
  license: MIT
  license_file: COPYING
  summary: GNUstep Objective-C 2.0 Runtime

extra:
  recipe-maintainers:
    - ethanc8
