context:
  name: gnustep-systempreferences
  version: 1.2.1
  tag: systempreferences-1_2_1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gnustep/apps-systempreferences/archive/refs/tags/${{ tag }}.tar.gz
    sha256: 40125db52808abef4a08433c43ab856dcad3c24f909531655fc794145fd2c8ab

build:
  number: 0
  skip: false
  script: build-systempreferences.sh

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ninja
  host:
    - ${{ stdlib('c') }}
    - gnustep-make
    - gnustep-libobjc2
    - gnustep-libdispatch
    - libgnustep-base
    - libgnustep-gui
    - libgnustep-back

about:
  homepage: https://github.com/gnustep/apps-systempreferences
  license: GPL-2.0-or-later
  license_file: 
    - COPYING
  summary: GNUstep configuration tool

extra:
  recipe-maintainers:
    - ethanc8
